USE [ServiceManagement_STG]
GO
/****** Object:  StoredProcedure [dbo].[load_RMD_FACT_HPD_HELP_DESK]    Script Date: 2/28/2023 11:16:02 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[load_RMD_FACT_HPD_HELP_DESK]
	
AS
BEGIN
	SET NOCOUNT ON;

DROP TABLE [ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK_PREVIOUS]

SELECT * INTO [ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK_PREVIOUS]
FROM [ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK]
	
DELETE FROM [ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK] where [INCIDENT_NUMBER] in
 (SELECT [INCIDENT_NUMBER (ID)] AS [INCIDENT NUMBER]
      FROM  [ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK]
  INNER JOIN [ServiceManagement_STG].[dbo].[STG_HPD_HELP_DESK_RECONCILE]
  ON [STG_HPD_HELP_DESK_RECONCILE].[INCIDENT_NUMBER (ID)] = [RMD_FACT_HPD_HELP_DESK].[INCIDENT_NUMBER]
  WHERE [STG_HPD_HELP_DESK_RECONCILE].[ASSIGNED_SUPPORT_COMPANY (ID)] <> 'TELEFONICA UK'
  AND [STG_HPD_HELP_DESK_RECONCILE].[ASSIGNED_SUPPORT_COMPANY (ID)] <> 'VODAFONE UK'
  AND [STG_HPD_HELP_DESK_RECONCILE].[ASSIGNED_GROUP (ID)] <> 'AO_APP_ITSM')

DELETE FROM [ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK] where [INCIDENT_NUMBER] in
 (SELECT [INCIDENT_NUMBER (ID)] as [INCIDENT NUMBER] FROM [STG_HPD_HELP_DESK])

DELETE FROM [ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK_BEACON] where [INCIDENT_NUMBER] in
 (SELECT [INCIDENT_NUMBER (ID)] as [INCIDENT NUMBER] FROM [STG_HPD_HELP_DESK]) 

DECLARE @BST_LOG float
SET @BST_LOG = (Select [ETL_LOG_BST_OFFSET] from [STG_ETL_LOG_BST_OFFSET])

INSERT INTO [ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK]
SELECT DISTINCT
      CASE 
	  WHEN [STG_HPD_HELP_DESK].[ASSIGNEE] IS NULL THEN 'Not Selected'
	  ELSE [STG_HPD_HELP_DESK].[ASSIGNEE]
	  END
      ,[STG_HPD_HELP_DESK].[CITY]
      ,[STG_HPD_HELP_DESK].[COMPANY]
      ,[STG_HPD_HELP_DESK].[COUNTRY]
      ,[STG_HPD_HELP_DESK].[DEPARTMENT]
      ,[STG_HPD_HELP_DESK].[IMPACT]
      ,[STG_HPD_HELP_DESK].[INSTANCEID]
	  ,STG_SLM_MEASUREMENT_COMBINED.MEASUREMENTSTATUS_SLA1
	  ,CASE 
	  WHEN RMD_DIM_SLM_MEASUREMENT_STATUS.MET_SLA IS NULL AND [STG_SLM_MEASUREMENT_COMBINED].UPELAPSEDTIME_SLA1 = 0 THEN '1'
	  WHEN RMD_DIM_SLM_MEASUREMENT_STATUS.MET_SLA IS NULL AND [STG_SLM_MEASUREMENT_COMBINED].UPELAPSEDTIME_SLA1 IS NULL THEN '1'
	  WHEN RMD_DIM_SLM_MEASUREMENT_STATUS.MET_SLA IS NULL AND [STG_SLM_MEASUREMENT_COMBINED].UPELAPSEDTIME_SLA1 <> 0 THEN '4'
	  WHEN RMD_DIM_SLM_MEASUREMENT_STATUS.MET_SLA IS NULL AND [STG_SLM_MEASUREMENT_COMBINED].UPELAPSEDTIME_SLA1 IS NOT NULL THEN '4'
	  ELSE RMD_DIM_SLM_MEASUREMENT_STATUS.MET_SLA
	  END
	  ,STG_SLM_MEASUREMENT_COMBINED.MEASUREMENTSTATUS_SLA2
      ,[STG_HPD_HELP_DESK].[MANUFACTURER]
      ,[STG_HPD_HELP_DESK].[ORGANIZATION]
      ,[STG_HPD_HELP_DESK].[PRIORITY]
      ,[STG_HPD_HELP_DESK].[REGION]
      ,CASE 
	  WHEN [STG_HPD_HELP_DESK].[SERVICE] IS NULL THEN 'Not Selected'
	  ELSE [STG_HPD_HELP_DESK].[SERVICE]
	  END
	  ,CASE 
	  WHEN [STG_HPD_HELP_DESK].[SERVICECI] IS NULL THEN 'Not Selected'
	  ELSE [STG_HPD_HELP_DESK].[SERVICECI]
	  END
      ,[STG_HPD_HELP_DESK].[SITE]
      ,[STG_HPD_HELP_DESK].[STATUS]
      ,[STG_HPD_HELP_DESK].[SUBMITTER]
      ,[STG_HPD_HELP_DESK].[URGENCY]
      ,[STG_HPD_HELP_DESK].[ENTRY_ID (ID)]
      ,dbo.RemedyDate([STG_HPD_HELP_DESK].[SUBMIT_DATE (ID)])
      ,[STG_HPD_HELP_DESK].[ASSIGNEE_LOGIN_ID (ID)]
      ,[STG_HPD_HELP_DESK].[LAST_MODIFIED_BY (ID)]
      ,dbo.RemedyDate([STG_HPD_HELP_DESK].[LAST_MODIFIED_DATE (ID)])
      ,CASE 
		WHEN [STG_HPD_HELP_DESK].[SHORT_DESCRIPTION (ID)] IS NULL THEN 'Not Selected'
		WHEN [STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_COMPANY (ID)] = 'VODAFONE UK' THEN 'Beacon Redacted'
		ELSE [STG_HPD_HELP_DESK].[SHORT_DESCRIPTION (ID)]
		END
	  ,[STG_HPD_HELP_DESK].[ASSIGNEE_GROUPS (ID)]
      ,[STG_HPD_HELP_DESK].[PRODUCT_CATEGORIZATION_TIER_1 (ID)]
      ,[STG_HPD_HELP_DESK].[PRODUCT_CATEGORIZATION_TIER_2 (ID)]
      ,[STG_HPD_HELP_DESK].[PRODUCT_CATEGORIZATION_TIER_3 (ID)]
      ,[STG_HPD_HELP_DESK].[SITE_GROUP (ID)]
      ,[STG_HPD_HELP_DESK].[ASSIGNEE_ID (ID)]
      ,[STG_HPD_HELP_DESK].[CREATED_BY (ID)]
      ,dbo.RemedyDate([STG_HPD_HELP_DESK].[ORIGINAL_LAST_MODIFIED_DATE (ID)])
      ,[STG_HPD_HELP_DESK].[ORIGINAL_LAST_MODIFIED_BY (ID)]
      ,dbo.RemedyDate([STG_HPD_HELP_DESK].[ZD_NEXTDUEDATE_TIME (ID)])
      ,[STG_HPD_HELP_DESK].[Z1D_TEMPLATE_NAME (ID)]
      ,[STG_HPD_HELP_DESK].[STATE_PROVINCE (ID)]
      ,[STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)]
	  ,CASE 
	  WHEN charindex('-',[STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)])-2 < 0 THEN [STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)]
	  WHEN [STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)] LIKE '%Smart Meter%' THEN 'Smart Meter'
      WHEN [STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_COMPANY (ID)] = 'VODAFONE UK' THEN 'Vodafone'
	  WHEN left([STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)],charindex('-',[STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)])-2) in ('IT','TGT') THEN 'IT'
	  WHEN left([STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)],charindex('-',[STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)])-2) in ('Sales & Service') THEN 'Customer Services'
	  WHEN left([STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)],charindex('-',[STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)])-2) in ('Svc Mgt','Service Management') THEN 'Service Management'
	  ELSE left([STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)],charindex('-',[STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)])-2)
	  END
	  ,CASE 
	  WHEN charindex('-',[STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)])>charindex('-',[STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)],charindex('-',[STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)])+1) THEN SUBSTRING ([STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)],(charindex('-',[STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)])+2),(len([STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)])-(charindex('-',[STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)]))))
	  WHEN charindex('-',[STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)])<charindex('-',[STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)],charindex('-',[STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)])+1) THEN SUBSTRING([STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)],(charindex('-',[STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)])+2),(charindex('-',[STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)],charindex('-',[STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)])+1))-(charindex('-',[STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_ORGANIZATION (ID)]))-3)
	  ELSE [ASSIGNED_SUPPORT_ORGANIZATION (ID)]
	  END
      ,[STG_HPD_HELP_DESK].[ZIP_POSTAL_CODE (ID)]
	  ,REPLACE([STG_HPD_HELP_DESK].[ZIP_POSTAL_CODE (ID)], ' ', '')
      ,[STG_HPD_HELP_DESK].[SITE_ID (ID)]
      ,[STG_HPD_HELP_DESK].[ASSIGNED_GROUP_ID (ID)]
      ,[STG_HPD_HELP_DESK].[PERSON_ID (ID)]
      ,[STG_HPD_HELP_DESK].[CONTACT_COMPANY (ID)]
      ,[STG_HPD_HELP_DESK].[SERVICE_TYPE (ID)]
      ,CASE 
	  WHEN [STG_HPD_HELP_DESK].[STATUS_REASON (ID)] IS NULL THEN -1
	  ELSE [STG_HPD_HELP_DESK].[STATUS_REASON (ID)]
	  END	  
      ,[STG_HPD_HELP_DESK].[INCIDENT_NUMBER (ID)]
      ,[STG_HPD_HELP_DESK].[PRIORITY_WEIGHT (ID)]
      ,[STG_HPD_HELP_DESK].[ASSIGNED_GROUP (ID)]
      ,[STG_HPD_HELP_DESK].[OWNER_SUPPORT_ORGANIZATION (ID)]
      ,[STG_HPD_HELP_DESK].[VENDOR_NAME (ID)]
      ,[STG_HPD_HELP_DESK].[OWNER_GROUP (ID)]
      ,[STG_HPD_HELP_DESK].[OWNER_SUPPORT_COMPANY (ID)]
      ,[STG_HPD_HELP_DESK].[OWNER_GROUP_ID (ID)]
      ,dbo.RemedyDate([STG_HPD_HELP_DESK].[REPORTED_DATE (ID)])
      ,dbo.RemedyDate([STG_HPD_HELP_DESK].[RESPONDED_DATE (ID)])
      ,dbo.RemedyDate([STG_HPD_HELP_DESK].[LAST_ACKNOWLEDGED_DATE (ID)])
	  ,dbo.RemedyDate([STG_HPD_HELP_DESK].[LAST_RESOLVED_DATE (ID)])
      ,dbo.RemedyDate([STG_HPD_HELP_DESK].[CLOSED_DATE (ID)])
	  ,[STG_HPD_HELP_DESK].[SLM_PRIORITY (ID)]
      ,CASE 
	  WHEN [STG_HPD_HELP_DESK].[SLM_STATUS (ID)] IS NULL THEN -1
	  ELSE [STG_HPD_HELP_DESK].[SLM_STATUS (ID)]
	  END
      ,[STG_HPD_HELP_DESK].[GROUP_TRANSFERS (ID)]
      ,[STG_HPD_HELP_DESK].[TOTAL_TRANSFERS (ID)]
      ,[STG_HPD_HELP_DESK].[INDIVIDUAL_TRANSFERS (ID)]
      ,[STG_HPD_HELP_DESK].[RESOLUTION_CATEGORY_TIER_2 (ID)]
      ,[STG_HPD_HELP_DESK].[RESOLUTION_CATEGORY_TIER_3 (ID)]
      ,[STG_HPD_HELP_DESK].[CLOSURE_PRODUCT_CATEGORY_TIER1 (ID)]
      ,[STG_HPD_HELP_DESK].[CLOSURE_PRODUCT_CATEGORY_TIER2 (ID)]
      ,[STG_HPD_HELP_DESK].[CLOSURE_PRODUCT_CATEGORY_TIER3 (ID)]
      ,[STG_HPD_HELP_DESK].[CLOSURE_PRODUCT_NAME (ID)]
      ,[STG_HPD_HELP_DESK].[CLOSURE_PRODUCT_MODEL_VERSION (ID)]
      ,[STG_HPD_HELP_DESK].[CLOSURE_MANUFACTURER (ID)]
      ,dbo.RemedyDate([STG_HPD_HELP_DESK].[TGTUK_BCON_RESTOREDDATE (ID)])
      ,CASE 
	  WHEN [STG_HPD_HELP_DESK].[TGT_CI_ENVIRONMENTTYPE (ID)] IS NULL THEN -1
	  ELSE [STG_HPD_HELP_DESK].[TGT_CI_ENVIRONMENTTYPE (ID)]
	  END
	  ,dbo.RemedyDate([STG_HPD_HELP_DESK].[TGT_LASTASSIGNMENTDATE (ID)])
      ,case
	  When [STG_HPD_HELP_DESK].[TGTUK_NETCOOL_ALARM_FIRST_OCCU (ID)] is null then '1970/01/01'
	  Else dbo.RemedyDate([STG_HPD_HELP_DESK].[TGTUK_NETCOOL_ALARM_FIRST_OCCU (ID)])
	  END
      ,[STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_COMPANY (ID)]
      ,[STG_HPD_HELP_DESK].[RESOLUTION_CATEGORY (ID)]
	  ,CASE 
	  WHEN [STG_HPD_HELP_DESK].[HPD_CI (ID)] IS NULL THEN 'Not Selected'
	  ELSE [STG_HPD_HELP_DESK].[HPD_CI (ID)]
	  END
	  ,[STG_HPD_HELP_DESK].[TGTUK_HPD_ACTUALCLH (ID)]
	  ,[STG_HPD_FIRST_ASSIGNMENT].[FIRST_INDIVIDUAL_ASSIGNMENT]
	  ,[STG_HPD_LAST_ASSIGNMENT].[LAST_GROUP_ASSIGNMENT]
	  ,[STG_HPD_HELP_DESK].[OWNER_ID (ID)]
	  ,[STG_HPD_HELP_DESK].[CATEGORIZATION_TIER_1 (ID)]
	  ,[STG_HPD_HELP_DESK].[CATEGORIZATION_TIER_2 (ID)]
	  ,[STG_HPD_HELP_DESK].[CATEGORIZATION_TIER_3 (ID)]
	  ,[STG_SH_HPD_HELP_DESK].[RESOLVED_USER (ID)]
	  ,CASE 
	  WHEN [STG_HPD_HELP_DESK].[REPORTED_SOURCE (ID)] IS NULL THEN -1
	  ELSE [STG_HPD_HELP_DESK].[REPORTED_SOURCE (ID)]
	  END
	  ,CASE
		WHEN ([STG_HPD_HELP_DESK].[STATUS] = 4 or [STG_HPD_HELP_DESK].[STATUS] = 5 or [STG_HPD_HELP_DESK].[STATUS] = 6) 
		THEN datediff(d, dbo.RemedyDate([STG_HPD_HELP_DESK].[SUBMIT_DATE (ID)]), dbo.RemedyDate([STG_HPD_HELP_DESK].[LAST_RESOLVED_DATE (ID)]))
		ELSE datediff(d, dbo.RemedyDate([STG_HPD_HELP_DESK].[SUBMIT_DATE (ID)]), GETDATE())
	  END
	  ,CONVERT(INT, CONVERT(VARCHAR(8), dbo.RemedyDate([STG_HPD_HELP_DESK].[TGTUK_NETCOOL_ALARM_FIRST_OCCU (ID)]), 112))
	  ,CONVERT(INT, CONVERT(VARCHAR(8), dbo.RemedyDate([STG_HPD_HELP_DESK].[CLOSED_DATE (ID)]), 112))
	  ,CONVERT(INT, CONVERT(VARCHAR(8), dbo.RemedyDate([STG_HPD_HELP_DESK].[ZD_NEXTDUEDATE_TIME (ID)]), 112))
	  ,CONVERT(INT, CONVERT(VARCHAR(8), [STG_HPD_FIRST_ASSIGNMENT].[FIRST_INDIVIDUAL_ASSIGNMENT], 112))
	  ,CONVERT(INT, CONVERT(VARCHAR(8), dbo.RemedyDate([STG_HPD_HELP_DESK].[LAST_RESOLVED_DATE (ID)]), 112))
	  ,CONVERT(INT, CONVERT(VARCHAR(8), dbo.RemedyDate([STG_HPD_HELP_DESK].[TGTUK_BCON_RESTOREDDATE (ID)]), 112))
	  ,CONVERT(INT, CONVERT(VARCHAR(8), dbo.RemedyDate([STG_HPD_HELP_DESK].[SUBMIT_DATE (ID)]), 112))
	  ,dbo.RemedyDate([RMD_PBM_MIN_SUBMIT_DATE].[Min_PBI_Submit_Date])
	  ,[STG_HPD_HELP_DESK].[FIRST_NAME (ID)]
      ,[STG_HPD_HELP_DESK].[Middle_Initial (ID)]
      ,[STG_HPD_HELP_DESK].[LAST_NAME (ID)]
      ,[STG_HPD_HELP_DESK].[CORPORATE_ID (ID)]
      ,[STG_HPD_HELP_DESK].[STREET (ID)]
      ,[STG_HPD_HELP_DESK].[DIRECT_CONTACT_FIRST_NAME (ID)]
      ,[STG_HPD_HELP_DESK].[Direct_Contact_Middle_Initial (ID)]
      ,[STG_HPD_HELP_DESK].[DIRECT_CONTACT_LAST_NAME (ID)]
      ,[STG_HPD_HELP_DESK].[DIRECT_CONTACT_COMPANY (ID)]
      ,[STG_HPD_HELP_DESK].[Direct_Contact_Organization (ID)]
      ,[STG_HPD_HELP_DESK].[Direct_Contact_Department (ID)]
      ,[STG_HPD_HELP_DESK].[Direct_Contact_Site (ID)]
      ,[STG_HPD_HELP_DESK].[Direct_Contact_Region (ID)]
      ,[STG_HPD_HELP_DESK].[Direct_Contact_Site_Group (ID)]
      ,[STG_HPD_HELP_DESK].[Direct_Contact_Country (ID)]
      ,[STG_HPD_HELP_DESK].[Direct_Contact_CITY (ID)]
      ,[STG_HPD_HELP_DESK].[Direct_Contact_STATE_PROVINCE (ID)]
      ,[STG_HPD_HELP_DESK].[Direct_Contact_STREET (ID)]
      ,[STG_HPD_HELP_DESK].[Direct_Contact_ZIP_POSTAL_CODE (ID)]
	  ,[STG_HPD_HELP_DESK].[tgtuk_bcon_managingoperator (ID)]
	  ,CASE
	  WHEN [STG_SLM_MEASUREMENT_COMBINED].[GOALTIMEHR_SLA1] IS NULL THEN 0
	  ELSE [STG_SLM_MEASUREMENT_COMBINED].[GOALTIMEHR_SLA1]
	  END
	  ,[STG_HPD_HELP_DESK].[RESOLUTION (ID)]
	  ,CASE
	  WHEN [STG_SLM_MEASUREMENT_COMBINED].[UPELAPSEDTIME_SLA1] IS NULL THEN 0
	  ELSE [STG_SLM_MEASUREMENT_COMBINED].[UPELAPSEDTIME_SLA1]
	  END
	  ,CASE 
      WHEN STG_HPD_HELP_DESK.[SUBMITTER] = 'NETCOOL_OSS' and
	       STG_HPD_HELP_DESK.[LAST_MODIFIED_BY (ID)] = 'NETCOOL_OSS' and
		   (STG_SLM_MEASUREMENT_COMBINED.[UPELAPSEDTIME_SLA1] = 0 OR STG_SLM_MEASUREMENT_COMBINED.[UPELAPSEDTIME_SLA1] IS NULL)
		   THEN 1
      WHEN STG_HPD_HELP_DESK.[SUBMITTER] = 'Remedy Application Service' and
	       STG_HPD_HELP_DESK.[LAST_MODIFIED_BY (ID)] = 'Remedy Application Service' and
		   (STG_SLM_MEASUREMENT_COMBINED.[UPELAPSEDTIME_SLA1] = 0 OR STG_SLM_MEASUREMENT_COMBINED.[UPELAPSEDTIME_SLA1] IS NULL)
		   THEN 1
      ELSE 0 
	  END
	  ,CASE
	  WHEN [STG_SLM_MEASUREMENT_COMBINED].[SVTDUEDATE_SLA1] IS NULL THEN '1970/01/01'
	  ELSE [STG_SLM_MEASUREMENT_COMBINED].[SVTDUEDATE_SLA1]
	  END
	  ,CASE
	  WHEN [ServiceManagement].[dbo].[RMD_FACT_HPD_RESOLVED_COUNT].[RESOLVED_COUNT] IS NULL THEN 0
	  ELSE [ServiceManagement].[dbo].[RMD_FACT_HPD_RESOLVED_COUNT].[RESOLVED_COUNT]
	  END
	  ,CASE
		WHEN [Impact] = 1000 And [Urgency] = 1000  THEN 1
		WHEN [Impact] = 1000 And [Urgency] = 2000 THEN 2
		WHEN [Impact] = 1000 And [Urgency] = 3000 Then 3
		WHEN [Impact] = 1000 And [Urgency] = 4000 Then 4
		WHEN [Impact] = 2000 And [Urgency] = 1000 Then 2
		WHEN [Impact] = 2000 And [Urgency] = 2000 Then 3
		WHEN [Impact] = 2000 And [Urgency] = 3000 Then 4
		WHEN [Impact] = 2000 And [Urgency] = 4000 Then 5
		WHEN [Impact] = 3000 And [Urgency] = 1000 Then 3
		WHEN [Impact] = 3000 And [Urgency] = 2000 Then 4
		WHEN [Impact] = 3000 And [Urgency] = 3000 Then 5
		WHEN [Impact] = 3000 And [Urgency] = 4000 Then 6
		WHEN [Impact] = 4000 And [Urgency] = 1000 Then 4
		WHEN [Impact] = 4000 And [Urgency] = 2000 Then 5
		WHEN [Impact] = 4000 And [Urgency] = 3000 Then 6
		WHEN [Impact] = 4000 And [Urgency] = 4000 Then 6
		ELSE -1
		END
		,[STG_HPD_FIRST_GROUP_ASSIGNMENT].[FIRST_GROUP_ASSIGNMENT]
		,[STG_HPD_SECOND_GROUP_ASSIGNMENT].[SECOND_GROUP_ASSIGNMENT]
		,0
		,[STG_HPD_FIRST_GROUP_ASSIGNMENT].[FIRST_GROUP]
		,[STG_HPD_SECOND_GROUP_ASSIGNMENT].[SECOND_GROUP]
		,[STG_HPD_WORKLOG_PRIORITY_INITIAL].[Priority_Original]
		,CASE
		WHEN [STG_HPD_HELP_DESK].[TGTUK_SMIP_DCC_INCIDENT_ID (ID)] IS NULL THEN 'Not Selected'
		ELSE [STG_HPD_HELP_DESK].[TGTUK_SMIP_DCC_INCIDENT_ID (ID)]
		END
        ,CASE
		WHEN [STG_HPD_HELP_DESK].[TGTUK_SMIP_ORIGINAL_DCC_PRIORI (ID)] IS NULL THEN -1
		ELSE [STG_HPD_HELP_DESK].[TGTUK_SMIP_ORIGINAL_DCC_PRIORI (ID)]
		END
        ,CASE
		WHEN [STG_HPD_HELP_DESK].[TGTUK_SMIP_CURRENTDCC_PRIORITY (ID)] IS NULL THEN -1
		ELSE [STG_HPD_HELP_DESK].[TGTUK_SMIP_CURRENTDCC_PRIORITY (ID)]
		END
        ,CASE 
		WHEN [STG_HPD_HELP_DESK].[DETAILED_DECRIPTION (ID)] IS NULL THEN 'Not Selected'
		WHEN [STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_COMPANY (ID)] = 'VODAFONE UK' THEN 'Beacon Redacted'
		ELSE left([STG_HPD_HELP_DESK].[DETAILED_DECRIPTION (ID)], 750)
		END
		,CASE 
		WHEN [RMD_FACT_HPD_WORKLOG_CELLS_OOS].[WL_DETAIL] IS NULL THEN 'Not Selected'
		ELSE SUBSTRING(SUBSTRING([WL_DETAIL],CHARINDEX('Cells OOS',[WL_DETAIL]),200),1,CHARINDEX('Alarm Details',SUBSTRING([WL_DETAIL],CHARINDEX('Cells OOS',[WL_DETAIL])+2,200)))
		END,
		CASE
		WHEN [Impact] = 1000 And [Urgency] = 1000 THEN 'P1'
		WHEN [Impact] = 1000 And [Urgency] = 2000 THEN 'P1'
		WHEN [Impact] = 1000 And [Urgency] = 3000 Then 'P1'
		WHEN [Impact] = 1000 And [Urgency] = 4000 Then 'P2'
		WHEN [Impact] = 2000 And [Urgency] = 1000 Then 'P1'
		WHEN [Impact] = 2000 And [Urgency] = 2000 Then 'P1'
		WHEN [Impact] = 2000 And [Urgency] = 3000 Then 'P2'
		WHEN [Impact] = 2000 And [Urgency] = 4000 Then 'P3'
		WHEN [Impact] = 3000 And [Urgency] = 1000 Then 'P1'
		WHEN [Impact] = 3000 And [Urgency] = 2000 Then 'P1'
		WHEN [Impact] = 3000 And [Urgency] = 3000 Then 'P3'
		WHEN [Impact] = 3000 And [Urgency] = 4000 Then 'P4'
		WHEN [Impact] = 4000 And [Urgency] = 1000 Then 'P2'
		WHEN [Impact] = 4000 And [Urgency] = 2000 Then 'P3'
		WHEN [Impact] = 4000 And [Urgency] = 3000 Then 'P3'
		WHEN [Impact] = 4000 And [Urgency] = 4000 Then 'P4'
		ELSE 'PX'
		END
	    ,CASE 
		WHEN [RMD_FACT_HPD_WORKLOG_CELLS_OOS].[WL_SUBMITTER] IS NULL THEN 'Not Selected'
		ELSE [RMD_FACT_HPD_WORKLOG_CELLS_OOS].[WL_SUBMITTER]
		END
		,CASE 
		WHEN [RMD_FACT_HPD_WORKLOG_CELLS_OOS].[WORK_LOG_DATE] IS NULL THEN '1970/01/01'
		ELSE [RMD_FACT_HPD_WORKLOG_CELLS_OOS].[WORK_LOG_DATE]
		END
		,[STG_HPD_HELP_DESK_MSF].[TGTUK_MSF_WHATSTHEINC (ID)]
		,[STG_HPD_HELP_DESK_MSF].[TGTUK_MSF_WHATSTHEIMPACTONT001 (ID)]
		,[STG_HPD_HELP_DESK_MSF].[TGTUK_MSF_WHATSTHEIMPACTONT002 (ID)]
		,[STG_SH_HPD_HELP_DESK].[CLOSED_USER (ID)]
		,[STG_HPD_HELP_DESK].[PRODUCT_NAME (ID)]
		
		
		,CASE 
		WHEN [STG_HPD_HELP_DESK].[TGTUK_SMIP_DCC_NOTIFICATIONDAT (ID)] IS NULL THEN '1970/01/01'
		ELSE dbo.RemedyDate([STG_HPD_HELP_DESK].[TGTUK_SMIP_DCC_NOTIFICATIONDAT (ID)])
		END
		,CASE 
		WHEN [STG_HPD_HELP_DESK].[TGTUK_SMIP_DCC_RESPONSEDATE (ID)] IS NULL THEN '1970/01/01'
		ELSE dbo.RemedyDate([STG_HPD_HELP_DESK].[TGTUK_SMIP_DCC_RESPONSEDATE (ID)])
		END
		,CASE
		WHEN [STG_HPD_HELP_DESK].[TGTUK_SMIP_INVALIDASSIGNMENT (ID)] IS NULL THEN '0'
		ELSE [STG_HPD_HELP_DESK].[TGTUK_SMIP_INVALIDASSIGNMENT (ID)]
		END
		,CASE
		WHEN [STG_HPD_HELP_DESK].[TGTUK_SMIP_ISSMIP_INC (ID)] IS NULL THEN '0'
		ELSE [STG_HPD_HELP_DESK].[TGTUK_SMIP_ISSMIP_INC (ID)]
		END
		,CASE
		WHEN [STG_HPD_HELP_DESK].[TGTUK_SMIP_NUMBERIMPACTEDCH (ID)] IS NULL THEN '0'
		ELSE [STG_HPD_HELP_DESK].[TGTUK_SMIP_NUMBERIMPACTEDCH (ID)]
		END
		,CASE
		WHEN [STG_HPD_HELP_DESK].[TGTUK_SMIP_NUMBEROFCOMMSHUB001 (ID)] IS NULL THEN '0'
		ELSE [STG_HPD_HELP_DESK].[TGTUK_SMIP_NUMBEROFCOMMSHUB001 (ID)]
		END
		,CASE
		WHEN [STG_HPD_HELP_DESK].[TGTUK_SMIP_NUMBEROFCOMMSHUB002 (ID)] IS NULL THEN '0'
		ELSE [STG_HPD_HELP_DESK].[TGTUK_SMIP_NUMBEROFCOMMSHUB002 (ID)]
		END
		,CASE
		WHEN [STG_HPD_HELP_DESK].[TGTUK_SMIP_NUMBEROFCOMMSHUBSSW (ID)] IS NULL THEN '0'
		ELSE [STG_HPD_HELP_DESK].[TGTUK_SMIP_NUMBEROFCOMMSHUBSSW (ID)]
		END
		,CASE
		WHEN [STG_HPD_HELP_DESK].[TGTUK_SMIP_NUMBEROFCOMMSHUBSTO (ID)] IS NULL THEN '0'
		ELSE [STG_HPD_HELP_DESK].[TGTUK_SMIP_NUMBEROFCOMMSHUBSTO (ID)]
		END
		,CASE
		WHEN [STG_HPD_HELP_DESK].[TGTUK_SMIP_EXCEPTIONREASONCODE (ID)] IS NULL THEN 'Not Selected'
		ELSE [STG_HPD_HELP_DESK].[TGTUK_SMIP_EXCEPTIONREASONCODE (ID)]
		END
		,CASE
		WHEN [STG_HPD_HELP_DESK].[TGTUK_SMIP_CSP_REGION (ID)] IS NULL THEN 'Not Selected'
		ELSE [STG_HPD_HELP_DESK].[TGTUK_SMIP_CSP_REGION (ID)]
		END
		,CASE
		WHEN [STG_HPD_HELP_DESK].[TGTUK_SMIP_COMMHUBGUID (ID)] IS NULL THEN 'Not Selected'
		ELSE [STG_HPD_HELP_DESK].[TGTUK_SMIP_COMMHUBGUID (ID)]
		END
		,CASE
		WHEN [STG_HPD_HELP_DESK].[TGTUK_SMIP_ASSOCIATEDPOSTCODES (ID)] IS NULL THEN 'Not Selected'
		ELSE [STG_HPD_HELP_DESK].[TGTUK_SMIP_ASSOCIATEDPOSTCODES (ID)]
		END
		,CASE
		WHEN [STG_HPD_INCIDENTINTERFACE].[REQUEST_ID (ID)] IS NULL THEN 'Not Selected'
		ELSE [STG_HPD_INCIDENTINTERFACE].[REQUEST_ID (ID)]
		END,
		[STG_HPD_HELP_DESK].[SRID],
		[STG_HPD_HELP_DESK].[OWNER_LOGIN_ID],
		[STG_SLM_MEASUREMENT_COMBINED_SMIP].[UPELAPSEDTIME_SLA1],
		[STG_SLM_MEASUREMENT_COMBINED_SMIP].[UPELAPSEDTIME_SLA2],
		[STG_SLM_MEASUREMENT_COMBINED_SMIP].[UPELAPSEDTIME_SLA3],
		[STG_HPD_HELP_DESK].[TGTUK_NETCOOL_ALARMKEY (ID)],
        [STG_HPD_HELP_DESK].[TGTUK_NETCOOL_CLASSNAME (ID)],
        [STG_HPD_HELP_DESK].[TGTUK_NETCOOL_PRODUCT_CATEGORY (ID)],
        [STG_HPD_HELP_DESK].[TGTUK_NETCOOL_ALARMSEVERITY1 (ID)],
        [STG_HPD_HELP_DESK].[TGTUK_NETCOOL_CLASSID1 (ID)],
        [STG_HPD_HELP_DESK].[TGTUK_NETCOOL_SERVERSERIAL1 (ID)],
		dbo.RemedyDate([STG_HPD_HELP_DESK].[REQUIRED_RESOLUTION_DATETIME (ID)]),
		[STG_SLM_MEASUREMENT_BT].[UPELAPSEDTIME (ID)],
		      [STG_HPD_HELP_DESK_MSF].[TGTUK_MSF_CUSTTITLE (ID)],
     dbo.RemedyDate([STG_HPD_HELP_DESK_MSF].[TGTUK_MSF_STARTON (ID)]),
     dbo.RemedyDate([STG_HPD_HELP_DESK_MSF].[TGTUK_MSF_ESTFIXTIME (ID)]),
	  [STG_HPD_HELP_DESK].[INC_VENDOR_TICKET_NUMBER (ID)],
	dbo.RemedyDate([STG_HPD_HELP_DESK].[INC_TARGET_DATE (ID)])


  FROM [ServiceManagement_STG].[dbo].[STG_HPD_HELP_DESK]
  LEFT OUTER JOIN [ServiceManagement_STG].[dbo].[STG_HPD_FIRST_ASSIGNMENT]
  ON [STG_HPD_HELP_DESK].[INCIDENT_NUMBER (ID)] = [STG_HPD_FIRST_ASSIGNMENT].[INCIDENT_NUMBER]
  LEFT OUTER JOIN [ServiceManagement_STG].[dbo].[STG_HPD_FIRST_GROUP_ASSIGNMENT]
  ON [STG_HPD_HELP_DESK].[INCIDENT_NUMBER (ID)] = [STG_HPD_FIRST_GROUP_ASSIGNMENT].[INCIDENT_NUMBER]
  LEFT OUTER JOIN [ServiceManagement_STG].[dbo].[STG_HPD_SECOND_GROUP_ASSIGNMENT]
  ON [STG_HPD_HELP_DESK].[INCIDENT_NUMBER (ID)] = [STG_HPD_SECOND_GROUP_ASSIGNMENT].[INCIDENT_NUMBER]
  LEFT OUTER JOIN [ServiceManagement_STG].[dbo].[STG_HPD_LAST_ASSIGNMENT]
  ON [STG_HPD_HELP_DESK].[INCIDENT_NUMBER (ID)] = [STG_HPD_LAST_ASSIGNMENT].[INCIDENT_NUMBER]
  LEFT OUTER JOIN [ServiceManagement_STG].[dbo].[STG_SLM_MEASUREMENT_COMBINED]
  ON STG_HPD_HELP_DESK.INSTANCEID = STG_SLM_MEASUREMENT_COMBINED.INSTANCEID
  LEFT OUTER JOIN [ServiceManagement].[dbo].[RMD_DIM_SLM_MEASUREMENT_STATUS]
  ON STG_SLM_MEASUREMENT_COMBINED.MEASUREMENTSTATUS_SLA1 = RMD_DIM_SLM_MEASUREMENT_STATUS.MEASUREMENT_STATUS
  LEFT OUTER JOIN [ServiceManagement_STG].[dbo].[STG_SH_HPD_HELP_DESK]
  ON [STG_HPD_HELP_DESK].[ENTRY_ID (ID)] = STG_SH_HPD_HELP_DESK.[ENTRY_ID (ID)]
  LEFT OUTER JOIN [ServiceManagement_STG].[dbo].[RMD_PBM_MIN_SUBMIT_DATE]
  ON [STG_HPD_HELP_DESK].[INCIDENT_NUMBER (ID)] = [RMD_PBM_MIN_SUBMIT_DATE].[INCIDENT_NUMBER]
  LEFT OUTER JOIN [ServiceManagement].[dbo].[RMD_FACT_HPD_RESOLVED_COUNT]
  ON [ServiceManagement].[dbo].[RMD_FACT_HPD_RESOLVED_COUNT].[Incident_Number] = [STG_HPD_HELP_DESK].[INCIDENT_NUMBER (ID)]
  LEFT OUTER JOIN [ServiceManagement_STG].[dbo].[STG_HPD_WORKLOG_PRIORITY_INITIAL]
  ON [ServiceManagement_STG].[dbo].[STG_HPD_WORKLOG_PRIORITY_INITIAL].[Incident_Number] = [STG_HPD_HELP_DESK].[INCIDENT_NUMBER (ID)]
  LEFT OUTER JOIN [ServiceManagement].[dbo].[RMD_FACT_HPD_WORKLOG_CELLS_OOS]
  ON [STG_HPD_HELP_DESK].[INCIDENT_NUMBER (ID)] = [RMD_FACT_HPD_WORKLOG_CELLS_OOS].[INCIDENT_NUMBER]
  LEFT OUTER JOIN [ServiceManagement_STG].[dbo].[STG_HPD_HELP_DESK_MSF]
  ON [STG_HPD_HELP_DESK].[INCIDENT_NUMBER (ID)] = [STG_HPD_HELP_DESK_MSF].[INCIDENT_NUMBER (ID)]
  LEFT OUTER JOIN [ServiceManagement_STG].[dbo].[STG_HPD_INCIDENTINTERFACE]
  ON [STG_HPD_HELP_DESK].[INCIDENT_NUMBER (ID)] = [STG_HPD_INCIDENTINTERFACE].[INCIDENT_NUMBER (ID)]
  LEFT OUTER JOIN [ServiceManagement_STG].[dbo].[STG_SLM_MEASUREMENT_COMBINED_SMIP]
  ON STG_HPD_HELP_DESK.INSTANCEID = STG_SLM_MEASUREMENT_COMBINED_SMIP.INSTANCEID
  LEFT OUTER JOIN [ServiceManagement_STG].[dbo].[STG_SLM_MEASUREMENT_BT]
  ON STG_HPD_HELP_DESK.INSTANCEID = [STG_SLM_MEASUREMENT_BT].[INSTANCEID]

INSERT INTO [ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK_BEACON]
SELECT DISTINCT
      [STG_HPD_HELP_DESK].[INCIDENT_NUMBER (ID)]
	  ,[STG_HPD_HELP_DESK].[SHORT_DESCRIPTION (ID)]
      ,CASE
      WHEN [STG_HPD_HELP_DESK].[DETAILED_DECRIPTION (ID)] IS NULL THEN 'Not Selected'
		ELSE left([STG_HPD_HELP_DESK].[DETAILED_DECRIPTION (ID)], 750)
		END
  FROM [ServiceManagement_STG].[dbo].[STG_HPD_HELP_DESK]
  WHERE [STG_HPD_HELP_DESK].[ASSIGNED_SUPPORT_COMPANY (ID)] = 'VODAFONE UK'

DELETE FROM [ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK_BEACON]
WHERE [RMD_FACT_HPD_HELP_DESK_BEACON].[INCIDENT_NUMBER] NOT IN
(SELECT [INCIDENT_NUMBER] FROM [ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK])

EXEC [ServiceManagement_STG].[dbo].[load_RMD_FACT_HPD_HELP_DESK_INCIDENT_HOURS]
EXEC [ServiceManagement_STG].[dbo].[load_RMD_FACT_HPD_HELP_DESK_INCIDENT_ASSIGNMENT]
EXEC [ServiceManagement_STG].[dbo].[load_RMD_FACT_SMIP_EXCEPTIONS]
EXEC [ServiceManagement_STG].[dbo].[load_RMD_FACT_SMIP_EXCLUSIONS]

Update [ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK]
set [SECOND_GROUP_ASSIGNMENT] = [FIRST_GROUP_ASSIGNMENT]
WHERE [SECOND_GROUP_ASSIGNMENT] IS NULL and [FIRST_GROUP_ASSIGNMENT] IS NOT NULL

Update [ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK]
set [SECOND_GROUP] = [FIRST_GROUP]
WHERE [SECOND_GROUP] IS NULL and [FIRST_GROUP] IS NOT NULL

Update [ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK]
set [Priority_Original] = [PRIORITY_DESC]
FROM [ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK]
INNER JOIN [ServiceManagement].[dbo].[RMD_DIM_HPD_PRIORITY]
on [RMD_FACT_HPD_HELP_DESK].[PRIORITY] = [RMD_DIM_HPD_PRIORITY].[PRIORITY]
WHERE [Priority_Original] IS NULL

INSERT INTO [ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK_AUDIT]
SELECT [ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK].[INCIDENT_NUMBER],
[ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK].[LAST_MODIFIED_BY],
[ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK].[LAST_MODIFIED_DATE],
'TGT_CI_ENVIRONMENTTYPE' AS [AUDIT_FIELD],
[ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK_PREVIOUS].[TGT_CI_ENVIRONMENTTYPE] AS [PREVIOUS],
[ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK].[TGT_CI_ENVIRONMENTTYPE] AS [CURRENT]
FROM [ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK]
INNER JOIN [ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK_PREVIOUS]
ON [ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK].[INCIDENT_NUMBER] = [ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK_PREVIOUS].[INCIDENT_NUMBER]
WHERE [ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK].[TGT_CI_ENVIRONMENTTYPE] <> [ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK_PREVIOUS].[TGT_CI_ENVIRONMENTTYPE]

DELETE FROM [ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK_AUDIT]
  WHERE [LAST_MODIFIED_DATE] < getdate() - 730

TRUNCATE TABLE [ServiceManagement].[dbo].[YTM_MTH]

INSERT INTO [ServiceManagement].[dbo].[YTM_MTH] WITH (TABLOCK)
select dm.CalendarMthID,dm1.CalendarMthID from [ServiceManagement].[dbo].[DimMonth_MSTR] dm
inner join [ServiceManagement].[dbo].[DimMonth_MSTR] dm1
on dm.CalendarMthID>=dm1.CalendarMthID
AND DM.CalendarYear=DM1.CalendarYear
and dm.CalendarMthID<=  LEFT(CONVERT(varchar, GetDate(),112),6)

TRUNCATE TABLE [ServiceManagement].[dbo].[YTD_DAY]

INSERT INTO [ServiceManagement].[dbo].[YTD_DAY] WITH (TABLOCK)
select DM.DATEKEY,DM1.DATEKEY from [ServiceManagement].[dbo].[DimDate_MSTR] dm
inner join [ServiceManagement].[dbo].[DimDate_MSTR] dm1
on dm.DATEKEY>=dm1.DATEKEY
AND DM.CalendarYear=DM1.CalendarYear
and dm.DATEKEY<= LEFT(CONVERT(varchar, GetDate(),112),8)
order by dm.DATEKEY

  DECLARE @SourceRowCount int
  DECLARE @TargetRowCount int

set @SourceRowCount = (SELECT COUNT(*) FROM [ServiceManagement_STG].[dbo].[STG_HPD_HELP_DESK])
set @TargetRowCount = (SELECT COUNT(*) FROM [ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK])

INSERT INTO [ServiceManagement_STG].[dbo].[RMD_ETL_LOG]
VALUES ('[ServiceManagement_STG].[dbo].[STG_HPD_HELP_DESK]','[ServiceManagement].[dbo].[RMD_FACT_HPD_HELP_DESK]',Getdate()+@BST_LOG,@SourceRowCount,@TargetRowCount)

DELETE FROM [ServiceManagement_STG].[dbo].[RMD_ETL_LOG]
  WHERE [LoadTime] < getdate() - 90  

END 






